"""Block-diagram logic for OpenG 'Build Path (traditional)'.

Generated by lvkit's deterministic graph->Python pass from
``Build Path__ogtk.vi`` (traditional instance). Pure Python: imports nothing
from the UI layer, so it stays testable, debuggable, and swappable — the front
panel binds to this, never the other way round.
"""

from __future__ import annotations

from pathlib import Path
from typing import NamedTuple


class BuildPathResult(NamedTuple):
    appended_path: Path


def build_path(
    base_path: str | Path, name_or_relative_path: str | Path
) -> BuildPathResult:
    appended_path = Path(base_path) / name_or_relative_path
    return BuildPathResult(appended_path=appended_path)
