"""Index page rendering mixin for HTMLDocGenerator.

Methods: _render_index_page.
"""

from __future__ import annotations

from typing import TYPE_CHECKING


class IndexPageMixin:
    """Mixin providing the top-level index/table-of-contents page."""

    # These attributes are defined on HTMLDocGenerator in core.py
    doc_title: str
    doc_type: str
    icon_map: dict[str, str]
    class_pages: dict[str, str]

    if TYPE_CHECKING:
        # Stubs for methods defined on other mixins, resolved via MRO
        def _extract_library_group(self, vi_name: str) -> str: ...
        def _vi_name_to_filename(self, vi_name: str) -> str: ...
        def _extract_display_name(self, vi_name: str) -> str: ...

    def _render_index_page(self, all_vis: list[str]) -> str:
        """Render index page with table of contents, grouped by library."""
        # Group VIs by library
        grouped_vis: dict[str, list[str]] = {}
        for vi_name in all_vis:
            library = self._extract_library_group(vi_name)
            if library not in grouped_vis:
                grouped_vis[library] = []
            grouped_vis[library].append(vi_name)

        # Sort libraries and VIs within each library
        sorted_libraries = sorted(grouped_vis.keys())

        # Build grouped sections as accordions
        library_sections = []
        for library in sorted_libraries:
            vis_in_library = sorted(grouped_vis[library])
            vi_links = []
            for vi_name in vis_in_library:
                link = self._vi_name_to_filename(vi_name)
                display_name = self._extract_display_name(vi_name)
                # Get icon path (adjust from VI page relative to index relative)
                icon_html = ""
                if vi_name in self.icon_map:
                    # icon_map has "../icons/..." for VI pages; index needs "icons/..."
                    icon_path = self.icon_map[vi_name].replace("../", "")
                    icon_html = f'<img src="{icon_path}" alt="" class="vi-icon-small">'
                vi_links.append(
                    f'<li>{icon_html}<a href="{link}">{display_name}</a></li>'
                )

            vi_count = len(vis_in_library)
            vi_plural = "s" if vi_count != 1 else ""
            # Class group headers link to the class's landing page.
            if library in self.class_pages:
                library_name_html = (
                    f'<a href="{self.class_pages[library]}">{library}</a>'
                )
            else:
                library_name_html = library
            library_sections.append(f"""
            <details class="library-accordion" open>
                <summary class="library-header">
                    <div class="library-header-content">
                        <span class="library-name">{library_name_html}</span>
                        <span class="library-count">{vi_count} VI{vi_plural}</span>
                    </div>
                </summary>
                <ul class="vi-list">
                    {"".join(vi_links)}
                </ul>
            </details>
            """)

        lib_count = len(sorted_libraries)
        lib_word = "library" if lib_count == 1 else "libraries"
        toc_summary = f"Total VIs: {len(all_vis)} across {lib_count} {lib_word}"

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{self.doc_title} - Documentation</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <header>
        <h1>{self.doc_title}</h1>
        <p class="subtitle">{self.doc_type.capitalize()} Documentation</p>
    </header>

    <main>
        <section id="toc">
            <h2>Table of Contents</h2>
            <p>{toc_summary}</p>
            {"".join(library_sections)}
        </section>
    </main>

    <footer>
        <p>Generated by lvkit generate_documents</p>
        <p class="trademark">LabVIEW, NI, and National Instruments are trademarks of
        National Instruments Corporation. lvkit is an independent project, not
        affiliated with, authorized by, endorsed by, or sponsored by NI.</p>
    </footer>
</body>
</html>
"""
