"""HTML documentation generator for LabVIEW VIs."""

from __future__ import annotations

from pathlib import Path
from typing import Any


class HTMLDocGenerator:
    """Generate static HTML documentation for VIs."""

    def __init__(self, output_dir: Path, doc_title: str, doc_type: str):
        """Initialize HTML generator.

        Args:
            output_dir: Directory to write HTML files
            doc_title: Title for the documentation (library/class name)
            doc_type: Type of documentation ("library", "class", "directory")
        """
        self.output_dir = output_dir
        self.doc_title = doc_title
        self.doc_type = doc_type
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_vi_page(self, vi_data: dict[str, Any]) -> None:
        """Generate HTML page for a single VI.

        Args:
            vi_data: Dictionary with VI information (name, controls, indicators, etc.)
        """
        vi_name = vi_data["vi_name"]
        html_filename = self._vi_name_to_filename(vi_name)
        html_path = self.output_dir / html_filename

        html = self._render_vi_page(vi_data)

        html_path.write_text(html, encoding="utf-8")

    def generate_index_page(
        self, all_vis: list[str], cross_refs: dict[str, Any]
    ) -> None:
        """Generate index.html with table of contents.

        Args:
            all_vis: List of all VI names
            cross_refs: Cross-reference dictionary
        """
        html = self._render_index_page(all_vis)
        index_path = self.output_dir / "index.html"
        index_path.write_text(html, encoding="utf-8")

    def write_assets(self) -> None:
        """Write CSS and other static assets."""
        css = self._get_css()
        css_path = self.output_dir / "style.css"
        css_path.write_text(css, encoding="utf-8")

    def _render_vi_page(self, vi_data: dict[str, Any]) -> str:
        """Render VI page HTML."""
        vi_name = vi_data["vi_name"]
        controls = vi_data.get("controls", [])
        indicators = vi_data.get("indicators", [])
        dependencies = vi_data.get("dependencies", {})
        callers = vi_data.get("callers", [])
        graph = vi_data.get("graph", {})

        # Build sections
        controls_html = self._render_controls_table(controls)
        indicators_html = self._render_indicators_table(indicators)
        dependencies_html = self._render_dependencies_section(dependencies)
        callers_html = self._render_callers_section(callers)
        dataflow_html = self._render_dataflow_diagram(graph)

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{vi_name} - {self.doc_title}</title>
    <link rel="stylesheet" href="style.css">
    <script type="module">
        import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs';
        mermaid.initialize({{ startOnLoad: true, theme: 'default' }});
        await mermaid.contentLoaded();
    </script>
</head>
<body>
    <nav class="breadcrumb">
        <a href="index.html">{self.doc_title}</a> / <span>{vi_name}</span>
    </nav>

    <header>
        <h1>{vi_name}</h1>
        <p class="vi-type">{self.doc_type.capitalize()}</p>
    </header>

    <main>
        <section id="summary">
            <h2>Summary</h2>
            <p>Takes {len(controls)} input(s), returns {len(indicators)} output(s)</p>
        </section>

        <section id="inputs">
            <h2>Inputs (Controls)</h2>
            {controls_html}
        </section>

        <section id="outputs">
            <h2>Outputs (Indicators)</h2>
            {indicators_html}
        </section>

        <section id="dataflow">
            <h2>Block Diagram (Dataflow)</h2>
            {dataflow_html}
        </section>

        <section id="dependencies">
            <h2>Dependencies (Calls)</h2>
            {dependencies_html}
        </section>

        <section id="callers">
            <h2>Used By</h2>
            {callers_html}
        </section>
    </main>

    <footer>
        <p>Generated by vipy document_library</p>
    </footer>
</body>
</html>
"""

    def _render_controls_table(self, controls: list[dict[str, Any]]) -> str:
        """Render inputs table."""
        if not controls:
            return "<p>No inputs</p>"

        rows = []
        for ctrl in controls:
            default_val = ctrl.get("default_value")
            if default_val is None:
                default_val = "—"
            rows.append(
                f"""
            <tr>
                <td>{ctrl['name']}</td>
                <td><code>{ctrl['type']}</code></td>
                <td>{default_val}</td>
            </tr>
            """
            )

        return f"""
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Type</th>
                    <th>Default</th>
                </tr>
            </thead>
            <tbody>
                {''.join(rows)}
            </tbody>
        </table>
        """

    def _render_indicators_table(self, indicators: list[dict[str, Any]]) -> str:
        """Render outputs table."""
        if not indicators:
            return "<p>No outputs</p>"

        rows = []
        for ind in indicators:
            rows.append(
                f"""
            <tr>
                <td>{ind['name']}</td>
                <td><code>{ind['type']}</code></td>
            </tr>
            """
            )

        return f"""
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Type</th>
                </tr>
            </thead>
            <tbody>
                {''.join(rows)}
            </tbody>
        </table>
        """

    def _render_dependencies_section(self, dependencies: dict[str, str]) -> str:
        """Render dependencies with links."""
        if not dependencies:
            return "<p>No SubVI calls</p>"

        items = []
        for vi_name, description in dependencies.items():
            link = self._vi_name_to_filename(vi_name)
            items.append(
                f"""
            <li>
                <a href="{link}"><code>{vi_name}</code></a> - {description}
            </li>
            """
            )

        return f"""
        <ul class="dependency-list">
            {''.join(items)}
        </ul>
        """

    def _render_callers_section(self, callers: list[str]) -> str:
        """Render reverse links (who calls this VI)."""
        if not callers:
            return "<p>Not called by any VI in this documentation</p>"

        items = []
        for caller_name in callers:
            link = self._vi_name_to_filename(caller_name)
            items.append(
                f"""
            <li><a href="{link}"><code>{caller_name}</code></a></li>
            """
            )

        return f"""
        <ul class="caller-list">
            {''.join(items)}
        </ul>
        """

    def _render_dataflow_diagram(self, graph: dict[str, Any]) -> str:
        """Render Mermaid flowchart dataflow diagram."""
        nodes = graph.get("nodes", [])
        edges = graph.get("edges", [])

        if not nodes:
            return "<p>No dataflow graph available</p>"

        # Build Mermaid flowchart (left to right)
        lines = ["<pre class='mermaid'>", "flowchart LR"]

        # Define nodes with shapes based on type
        node_ids = {}
        for i, node in enumerate(nodes):
            node_id = f"n{i}"
            node_ids[node["id"]] = node_id
            node_type = node["type"]
            node_name = (node.get("name") or "").replace('"', "'")

            # Different shapes for different node types
            if node_type == "control":
                # Parallelogram for inputs
                lines.append(f'    {node_id}[/"{node_name}"/]')
            elif node_type == "indicator":
                # Parallelogram for outputs
                lines.append(f'    {node_id}[\\"{node_name}"\\]')
            elif node_type == "constant":
                # Rectangle with double border for constants
                lines.append(f'    {node_id}[["{node_name}"]]')
            elif node_type == "subvi":
                # Rounded rectangle for SubVIs
                lines.append(f'    {node_id}("{node_name}")')
            elif node_type == "primitive":
                # Rectangle for primitives
                lines.append(f'    {node_id}["{node_name}"]')
            else:
                # Default rectangle
                lines.append(f'    {node_id}["{node_name}"]')

        # Add edges (connections between nodes)
        for edge in edges:
            from_id = edge.get("from_node")
            to_id = edge.get("to_node")

            # Find parent nodes for these terminals
            from_parent = None
            to_parent = None

            for node in nodes:
                if node["id"] == from_id or from_id.startswith(node["id"]):
                    from_parent = node["id"]
                if node["id"] == to_id or to_id.startswith(node["id"]):
                    to_parent = node["id"]

            if from_parent and to_parent and from_parent in node_ids and to_parent in node_ids:
                lines.append(f'    {node_ids[from_parent]} --> {node_ids[to_parent]}')

        # Style nodes by type
        lines.append("    classDef controlStyle fill:#e1f5ff,stroke:#0288d1")
        lines.append("    classDef indicatorStyle fill:#fff9c4,stroke:#f57f17")
        lines.append("    classDef constantStyle fill:#f3e5f5,stroke:#7b1fa2")
        lines.append("    classDef subviStyle fill:#e8f5e9,stroke:#388e3c")
        lines.append("    classDef primitiveStyle fill:#fce4ec,stroke:#c2185b")

        for i, node in enumerate(nodes):
            node_id = f"n{i}"
            if node["type"] == "control":
                lines.append(f"    class {node_id} controlStyle")
            elif node["type"] == "indicator":
                lines.append(f"    class {node_id} indicatorStyle")
            elif node["type"] == "constant":
                lines.append(f"    class {node_id} constantStyle")
            elif node["type"] == "subvi":
                lines.append(f"    class {node_id} subviStyle")
            elif node["type"] == "primitive":
                lines.append(f"    class {node_id} primitiveStyle")

        lines.append("</pre>")
        return "\n".join(lines)

    def _render_index_page(self, all_vis: list[str]) -> str:
        """Render index page with table of contents."""
        vi_links = []
        for vi_name in sorted(all_vis):
            link = self._vi_name_to_filename(vi_name)
            vi_links.append(
                f"""
            <li><a href="{link}">{vi_name}</a></li>
            """
            )

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{self.doc_title} - Documentation</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <header>
        <h1>{self.doc_title}</h1>
        <p class="subtitle">{self.doc_type.capitalize()} Documentation</p>
    </header>

    <main>
        <section id="toc">
            <h2>Table of Contents</h2>
            <p>Total VIs: {len(all_vis)}</p>
            <ul class="vi-list">
                {''.join(vi_links)}
            </ul>
        </section>
    </main>

    <footer>
        <p>Generated by vipy document_library</p>
    </footer>
</body>
</html>
"""

    def _vi_name_to_filename(self, vi_name: str) -> str:
        """Convert VI name to safe HTML filename."""
        # Handle qualified names (Library.lvlib:VI.vi)
        safe_name = vi_name.replace(":", "_").replace("/", "_").replace("\\", "_")
        # Remove .vi extension if present
        safe_name = safe_name.replace(".vi", "").replace(".VI", "")
        # Replace spaces and other unsafe characters with underscores
        safe_name = safe_name.replace(" ", "_").replace("(", "_").replace(")", "_")
        safe_name = safe_name.replace("[", "_").replace("]", "_").replace("{", "_").replace("}", "_")
        safe_name = safe_name.replace("<", "_").replace(">", "_").replace("|", "_")
        safe_name = safe_name.replace("?", "_").replace("*", "_").replace('"', "_")
        # Remove any consecutive underscores
        while "__" in safe_name:
            safe_name = safe_name.replace("__", "_")
        return f"{safe_name}.html"

    def _get_css(self) -> str:
        """Return CSS stylesheet."""
        return """/* vipy documentation stylesheet */

:root {
    --primary-color: #2c3e50;
    --secondary-color: #3498db;
    --bg-color: #ecf0f1;
    --text-color: #2c3e50;
    --border-color: #bdc3c7;
    --code-bg: #f8f9fa;
}

* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, sans-serif;
    line-height: 1.6;
    color: var(--text-color);
    background: var(--bg-color);
    padding: 20px;
}

.breadcrumb {
    background: white;
    padding: 10px 20px;
    margin-bottom: 20px;
    border-radius: 5px;
    font-size: 14px;
}

.breadcrumb a {
    color: var(--secondary-color);
    text-decoration: none;
}

.breadcrumb a:hover {
    text-decoration: underline;
}

header {
    background: white;
    padding: 30px;
    border-radius: 5px;
    margin-bottom: 20px;
    box-shadow: 0 2px 4px rgba(0,0,0,0.1);
}

h1 {
    color: var(--primary-color);
    margin-bottom: 10px;
}

h2 {
    color: var(--primary-color);
    margin-top: 20px;
    margin-bottom: 10px;
    border-bottom: 2px solid var(--border-color);
    padding-bottom: 5px;
}

main {
    background: white;
    padding: 30px;
    border-radius: 5px;
    box-shadow: 0 2px 4px rgba(0,0,0,0.1);
}

section {
    margin-bottom: 30px;
}

table {
    width: 100%;
    border-collapse: collapse;
    margin: 15px 0;
}

table th,
table td {
    text-align: left;
    padding: 12px;
    border-bottom: 1px solid var(--border-color);
}

table th {
    background: var(--code-bg);
    font-weight: 600;
}

code {
    background: var(--code-bg);
    padding: 2px 6px;
    border-radius: 3px;
    font-family: "SF Mono", Monaco, "Courier New", monospace;
    font-size: 0.9em;
}

pre {
    background: var(--code-bg);
    padding: 15px;
    border-radius: 5px;
    overflow-x: auto;
    font-family: "SF Mono", Monaco, "Courier New", monospace;
}

ul, ol {
    margin-left: 30px;
    margin-top: 10px;
}

li {
    margin-bottom: 8px;
}

a {
    color: var(--secondary-color);
    text-decoration: none;
}

a:hover {
    text-decoration: underline;
}

.vi-type {
    color: #7f8c8d;
    font-size: 14px;
}

.subtitle {
    color: #7f8c8d;
    font-size: 18px;
}

footer {
    text-align: center;
    margin-top: 40px;
    color: #7f8c8d;
    font-size: 14px;
}

.dataflow {
    font-family: monospace;
    line-height: 1.4;
}

.dependency-list,
.caller-list,
.vi-list {
    list-style: none;
    margin-left: 0;
}

.dependency-list li,
.caller-list li,
.vi-list li {
    padding: 8px 0;
    border-bottom: 1px solid var(--border-color);
}

.dependency-list li:last-child,
.caller-list li:last-child,
.vi-list li:last-child {
    border-bottom: none;
}
"""
