"""Emit C from a parsed Formula Node script.

Produces a self-contained C translation unit (prelude + one ``formula``
function) plus an ordered signature spec the ctypes layer uses to marshal.

The emitter performs only the transformations a C compiler genuinely
requires (everything else is C already):
  * ``a ** b``                  -> ``lv_pow(a, b)``
  * LabVIEW type keywords       -> stdint/C types (``int16`` -> ``int16_t`` …)
  * formula function spellings  -> ``<math.h>`` / prelude helpers
  * ``x % y`` with a float side -> ``fmod(x, y)``
  * assignment into an int var  -> rounded (``lv_round``), matching LabVIEW

Unknown functions or type keywords raise FormulaTranspileError — never a
silent guess.
"""

from __future__ import annotations

from dataclasses import dataclass

from . import FormulaTranspileError
from .cparser import parse
from .nodes import (
    Assign,
    Binary,
    Block,
    Call,
    Decl,
    DoWhile,
    Empty,
    Expr,
    ExprStmt,
    For,
    If,
    IncDec,
    Index,
    Num,
    Stmt,
    Unary,
    Var,
    While,
)

# --- type maps -------------------------------------------------------------

# LabVIEW numeric type-name (parser's ParsedType.type_name) -> C type / ctype.
_LV_C_TYPE = {
    "NumInt8": "int8_t", "NumInt16": "int16_t",
    "NumInt32": "int32_t", "NumInt64": "int64_t",
    "NumUInt8": "uint8_t", "NumUInt16": "uint16_t",
    "NumUInt32": "uint32_t", "NumUInt64": "uint64_t",
    "NumFloat32": "float", "NumFloat64": "double",
    "NumComplex64": None, "NumComplex128": None,
}
_LV_CTYPES = {
    "NumInt8": "c_int8", "NumInt16": "c_int16",
    "NumInt32": "c_int32", "NumInt64": "c_int64",
    "NumUInt8": "c_uint8", "NumUInt16": "c_uint16",
    "NumUInt32": "c_uint32", "NumUInt64": "c_uint64",
    "NumFloat32": "c_float", "NumFloat64": "c_double",
}
# ctypes name -> C element type, for emitting the C function signature.
_CTYPE_TO_C = {
    "c_int8": "int8_t", "c_int16": "int16_t", "c_int32": "int32_t",
    "c_int64": "int64_t", "c_uint8": "uint8_t", "c_uint16": "uint16_t",
    "c_uint32": "uint32_t", "c_uint64": "uint64_t",
    "c_float": "float", "c_double": "double",
}
# Formula-node declaration keyword -> C type. ``float`` is float64 (double).
_KW_C_TYPE = {
    "int8": "int8_t", "int16": "int16_t", "int32": "int32_t", "int64": "int64_t",
    "uInt8": "uint8_t", "uInt16": "uint16_t",
    "uInt32": "uint32_t", "uInt64": "uint64_t",
    "float32": "float", "float64": "double", "float": "double",
}
# Formula-node keyword -> abstract kind for type inference.
_KW_KIND = {k: ("float" if v in ("float", "double") else "int")
            for k, v in _KW_C_TYPE.items()}
_LV_KIND = {k: ("float" if v in ("float", "double") else "int")
            for k, v in _LV_C_TYPE.items() if v}

# Formula-node function spelling -> emitted C callee. Anything not here fails
# loud. Direct <math.h> names map to themselves.
_FUNC_MAP = {
    "abs": "fabs", "sqrt": "sqrt", "exp": "exp", "expm1": "expm1",
    "ln": "log", "lnp1": "log1p", "log": "log10", "log2": "log2",
    "ceil": "ceil", "floor": "floor",
    "sin": "sin", "cos": "cos", "tan": "tan",
    "asin": "asin", "acos": "acos", "atan": "atan", "atan2": "atan2",
    "sinh": "sinh", "cosh": "cosh", "tanh": "tanh",
    "asinh": "asinh", "acosh": "acosh", "atanh": "atanh",
    "pow": "pow",
    "int": "lv_int", "intrz": "lv_intrz",
    "mod": "lv_mod", "rem": "lv_rem", "sign": "lv_sign",
    "max": "lv_max", "min": "lv_min",
    "cot": "lv_cot", "csc": "lv_csc", "sec": "lv_sec", "sinc": "lv_sinc",
}
_INT_RESULT_FUNCS = {"int", "intrz", "sign"}

# Prelude inlined at the top of every generated .c so the file is
# self-contained (no separate header to ship alongside it).
PRELUDE = r"""/* Generated by lvkit from a LabVIEW Formula Node. Do not edit by hand. */
#include <stdint.h>
#include <math.h>

/* LabVIEW Formula Node round-to-nearest (ties to even), matching the
   node's implicit float->int coercion and the int() function. int()/intrz()
   return an integer type so results feed bitwise operators (& | ^ << >>). */
static inline double  lv_round(double x) { return rint(x); }
static inline int64_t lv_int(double x)   { return (int64_t)rint(x); }
static inline int64_t lv_intrz(double x) { return (int64_t)trunc(x); }
static inline double lv_pow(double b, double e) { return pow(b, e); }
static inline double lv_sign(double x)  { return (x > 0) - (x < 0); }
static inline double lv_mod(double a, double b) { return fmod(a, b); }
static inline double lv_rem(double a, double b) { return a - b * rint(a / b); }
static inline double lv_max(double a, double b) { return a > b ? a : b; }
static inline double lv_min(double a, double b) { return a < b ? a : b; }
static inline double lv_cot(double x)   { return 1.0 / tan(x); }
static inline double lv_csc(double x)   { return 1.0 / sin(x); }
static inline double lv_sec(double x)   { return 1.0 / cos(x); }
static inline double lv_sinc(double x)  { return x == 0.0 ? 1.0 : sin(x) / x; }
"""


@dataclass
class VarSpec:
    """One Formula Node variable (a wired terminal)."""
    name: str
    lv_type: str       # NumInt16/NumFloat64/... (element type for arrays)
    direction: str     # "in" | "out" | "inout"
    is_array: bool


@dataclass
class Param:
    """One C-function parameter, mirrored into the ctypes signature."""
    name: str          # C parameter identifier
    ctype: str         # ctypes name, e.g. "c_double"
    role: str          # array_in | array_inout | scalar_in | scalar_out | array_out
    var: str           # source VarSpec name (for marshaling)


@dataclass
class TranspileResult:
    c_source: str
    params: list[Param]
    func_name: str


class _Emitter:
    def __init__(self, variables: list[VarSpec], func_name: str):
        self.vars = {v.name: v for v in variables}
        self.var_list = variables
        self.func_name = func_name
        # abstract kind ("int"/"float") per variable name; locals added later.
        self.kind: dict[str, str] = {}
        for v in variables:
            k = _LV_KIND.get(v.lv_type)
            if k is None:
                raise FormulaTranspileError(
                    f"unsupported variable type {v.lv_type!r} for {v.name!r}")
            self.kind[v.name] = k

    # --- type inference (coarse: int vs float) ---

    def _texpr(self, e: Expr) -> str:
        if isinstance(e, Num):
            return "float" if e.is_float else "int"
        if isinstance(e, Var):
            return self.kind.get(e.name, "float")
        if isinstance(e, Index):
            return self.kind.get(e.name, "float")
        if isinstance(e, Call):
            return "int" if e.name in _INT_RESULT_FUNCS else "float"
        if isinstance(e, Unary):
            return self._texpr(e.operand)
        if isinstance(e, Binary):
            if e.op in ("<", "<=", ">", ">=", "==", "!=", "&&", "||"):
                return "int"
            if e.op in ("&", "|", "^", "<<", ">>"):
                return "int"
            if e.op in ("**", "/"):
                # Power and division always yield a float in a Formula Node
                # (int/int is real division).
                return "float"
            lt, rt = self._texpr(e.left), self._texpr(e.right)
            return "float" if "float" in (lt, rt) else "int"
        return "float"

    # --- expression emission ---

    def _emit_expr(self, e: Expr) -> str:
        if isinstance(e, Num):
            return e.text
        if isinstance(e, Var):
            if e.name == "pi":
                return "M_PI"
            return e.name
        if isinstance(e, Index):
            return f"{e.name}[{self._emit_expr(e.index)}]"
        if isinstance(e, Call):
            callee = _FUNC_MAP.get(e.name)
            if callee is None:
                raise FormulaTranspileError(
                    f"unsupported function {e.name!r}")
            args = ", ".join(self._emit_expr(a) for a in e.args)
            return f"{callee}({args})"
        if isinstance(e, Unary):
            return f"({e.op}{self._emit_expr(e.operand)})"
        if isinstance(e, Binary):
            left = self._emit_expr(e.left)
            right = self._emit_expr(e.right)
            if e.op == "**":
                return f"lv_pow({left}, {right})"
            if e.op == "%" and "float" in (self._texpr(e.left),
                                           self._texpr(e.right)):
                return f"fmod({left}, {right})"
            if e.op == "/":
                # Formula Node division is real division even for two
                # integers (int/int -> float); integer truncation only
                # happens at assignment to an integer variable. Force float
                # division by promoting the left operand to double.
                return f"((double)({left}) / ({right}))"
            # Fully parenthesize so C precedence never reshapes the AST.
            return f"({left} {e.op} {right})"
        raise FormulaTranspileError(f"cannot emit expression {e!r}")

    # --- helpers for assignment rounding ---

    def _target_kind(self, target: Var | Index) -> str | None:
        return self.kind.get(target.name)

    def _emit_rhs(self, target_kind: str | None, value: Expr) -> str:
        rhs = self._emit_expr(value)
        # LabVIEW rounds when a fractional value lands in an integer variable;
        # C would truncate. Round to match (skip when RHS is already integral).
        if target_kind == "int" and self._texpr(value) == "float":
            return f"lv_round({rhs})"
        return rhs

    # --- statement emission ---

    def _emit_stmt(self, s: Stmt, out: list[str], indent: int) -> None:
        pad = "    " * indent
        if isinstance(s, Empty):
            return
        if isinstance(s, Block):
            out.append(pad + "{")
            for inner in s.stmts:
                self._emit_stmt(inner, out, indent + 1)
            out.append(pad + "}")
            return
        if isinstance(s, Decl):
            self._emit_decl(s, out, indent)
            return
        if isinstance(s, Assign):
            tk = self._target_kind(s.target)
            tgt = self._emit_expr(s.target)
            out.append(f"{pad}{tgt} = {self._emit_rhs(tk, s.value)};")
            return
        if isinstance(s, IncDec):
            out.append(f"{pad}{s.name}{s.op};")
            return
        if isinstance(s, ExprStmt):
            out.append(f"{pad}{self._emit_expr(s.expr)};")
            return
        if isinstance(s, If):
            out.append(f"{pad}if ({self._emit_expr(s.cond)})")
            self._emit_block_or_stmt(s.then, out, indent)
            if s.orelse is not None:
                out.append(f"{pad}else")
                self._emit_block_or_stmt(s.orelse, out, indent)
            return
        if isinstance(s, While):
            out.append(f"{pad}while ({self._emit_expr(s.cond)})")
            self._emit_block_or_stmt(s.body, out, indent)
            return
        if isinstance(s, DoWhile):
            out.append(f"{pad}do")
            self._emit_block_or_stmt(s.body, out, indent)
            out.append(f"{pad}while ({self._emit_expr(s.cond)});")
            return
        if isinstance(s, For):
            init = self._inline_simple(s.init)
            cond = self._emit_expr(s.cond) if s.cond else ""
            post = self._inline_simple(s.post)
            out.append(f"{pad}for ({init}; {cond}; {post})")
            self._emit_block_or_stmt(s.body, out, indent)
            return
        raise FormulaTranspileError(f"cannot emit statement {s!r}")

    def _emit_block_or_stmt(self, s: Stmt, out: list[str], indent: int) -> None:
        # Always brace bodies: removes dangling-else ambiguity and keeps the
        # nearest-if binding the parser already resolved.
        pad = "    " * indent
        if isinstance(s, Block):
            self._emit_stmt(s, out, indent)
        else:
            out.append(pad + "{")
            self._emit_stmt(s, out, indent + 1)
            out.append(pad + "}")

    def _inline_simple(self, s: Stmt | None) -> str:
        """Render a for-init/post statement inline (no semicolon/indent)."""
        if s is None or isinstance(s, Empty):
            return ""
        if isinstance(s, Assign):
            tk = self._target_kind(s.target)
            return f"{self._emit_expr(s.target)} = {self._emit_rhs(tk, s.value)}"
        if isinstance(s, IncDec):
            return f"{s.name}{s.op}"
        if isinstance(s, ExprStmt):
            return self._emit_expr(s.expr)
        if isinstance(s, Decl):
            # single-item decl inline (for-init); rare
            buf: list[str] = []
            self._emit_decl(s, buf, 0)
            return buf[0].strip().rstrip(";")
        raise FormulaTranspileError("unsupported for-clause statement")

    def _emit_decl(self, s: Decl, out: list[str], indent: int) -> None:
        pad = "    " * indent
        for name, init in s.items:
            if name in self.vars:
                # Re-declaration of a terminal variable: it is already a
                # function-scope local. Drop the type; keep the initializer
                # as a plain assignment so the value is preserved.
                if init is not None:
                    tk = self.kind.get(name)
                    out.append(f"{pad}{name} = {self._emit_rhs(tk, init)};")
                continue
            ctype = _KW_C_TYPE.get(s.type_kw)
            if ctype is None:
                raise FormulaTranspileError(
                    f"unsupported type keyword {s.type_kw!r}")
            self.kind[name] = _KW_KIND[s.type_kw]
            if init is not None:
                rhs = self._emit_rhs(self.kind[name], init)
                out.append(f"{pad}{ctype} {name} = {rhs};")
            else:
                out.append(f"{pad}{ctype} {name};")

    # --- wrapper / signature ---

    def _collect_local_kinds(self, block: Block) -> None:
        """Pre-pass: record kinds of script-local declarations for inference."""
        def walk(s: Stmt) -> None:
            if isinstance(s, Decl):
                for name, _ in s.items:
                    if name not in self.vars:
                        self.kind.setdefault(name, _KW_KIND.get(s.type_kw, "float"))
            elif isinstance(s, Block):
                for i in s.stmts:
                    walk(i)
            elif isinstance(s, If):
                walk(s.then)
                if s.orelse:
                    walk(s.orelse)
            elif isinstance(s, (While, DoWhile)):
                walk(s.body)
            elif isinstance(s, For):
                if s.init:
                    walk(s.init)
                walk(s.body)
        for s in block.stmts:
            walk(s)

    def emit(self, tree: Block) -> TranspileResult:
        self._collect_local_kinds(tree)

        params: list[Param] = []
        prologue: list[str] = []
        epilogue: list[str] = []
        for v in self.var_list:
            c_elem = _LV_C_TYPE.get(v.lv_type)
            ctype = _LV_CTYPES.get(v.lv_type)
            if c_elem is None or ctype is None:
                raise FormulaTranspileError(
                    f"unsupported type {v.lv_type!r} for {v.name!r}")
            if v.is_array:
                role = {"in": "array_in", "out": "array_out",
                        "inout": "array_inout"}[v.direction]
                params.append(Param(v.name, ctype, role, v.name))
            elif v.direction == "in":
                params.append(Param(f"{v.name}_in", ctype, "scalar_in", v.name))
                prologue.append(f"    {c_elem} {v.name} = {v.name}_in;")
            elif v.direction == "out":
                params.append(Param(f"{v.name}_out", ctype, "scalar_out", v.name))
                prologue.append(f"    {c_elem} {v.name} = 0;")
                epilogue.append(f"    *{v.name}_out = {v.name};")
            else:  # inout scalar
                params.append(Param(f"{v.name}_in", ctype, "scalar_in", v.name))
                params.append(Param(f"{v.name}_out", ctype, "scalar_out", v.name))
                prologue.append(f"    {c_elem} {v.name} = {v.name}_in;")
                epilogue.append(f"    *{v.name}_out = {v.name};")

        body: list[str] = []
        for s in tree.stmts:
            self._emit_stmt(s, body, 1)

        sig = ", ".join(self._c_param(p) for p in params) or "void"
        lines = [PRELUDE, "", f"void {self.func_name}({sig})", "{"]
        lines.extend(prologue)
        if prologue:
            lines.append("")
        lines.extend(body)
        if epilogue:
            lines.append("")
            lines.extend(epilogue)
        lines.append("}")
        return TranspileResult("\n".join(lines) + "\n", params, self.func_name)

    def _c_param(self, p: Param) -> str:
        ct = _CTYPE_TO_C[p.ctype]
        if p.role == "scalar_in":
            return f"{ct} {p.name}"
        # arrays (any direction) and scalar_out are pointers
        return f"{ct} *{p.name}"


def transpile(
    script: str, variables: list[VarSpec], func_name: str = "formula",
) -> TranspileResult:
    """Transpile a Formula Node script to a self-contained C unit.

    ``variables`` are the node's wired terminals (deduped so a name wired on
    both sides is one ``inout`` entry). Raises FormulaTranspileError on any
    unsupported construct.
    """
    tree = parse(script)
    return _Emitter(variables, func_name).emit(tree)
